[#always-on-is-for-databases]
== Always-on is for Databases

Always-on is great for databases but not for you. Yet, you emit a constant green status icon. You promptly open and refresh your inbox on an interval so frequent and consistent that the behavior is indistinguishable from a bot. You treat direct messages like the closing of a million-dollar deal, replying with the utmost haste. You avoid offline and away status because responsiveness is rewarded above performance, driving you to constantly pull for information. You’re plugged in, but not productive.

Feeling obligated, you pour what was once commute time into work. It feels justified because in the absence of in-person interaction, there is an instinct to connect. Attempting to fill that void, you don’t question the increasing number of meetings. You yearn for a direct message. An email that was once a foe has become your friend. What were once distractions are now what keep you sane. You feel better about them but are they any less distracting? Attending zoom calls, scrolling feeds, liking posts, and thoughtlessly replying does little to provide meaning in one’s life. You find that genuine interpersonal communication cannot be so easily replaced.

The chaos of a busy office has been transplanted into the virtual world. But without the walls of an office to confine it, you’re left defenseless without boundaries. Zoom’s abuse displays our favoritism of synchronous communication and obsession with collaboration. Both the instinct to connect and the expectation of a real-time response are at the core of why you’re unproductive. It worked well enough while the world was in an office. Walls and exit signs kept it confined to set hours of our lives per day. But without those boundaries, maintaining that level of availability is unrealistic. Not only is it unrealistic, but it’s also dangerous. Heather De-Quincey tweeted “I think we need to stop calling it ‘working from home’ and start calling it ‘living at work’”. Is this how we want to live our lives? Do you want to put in more hours and be less productive? Or is it possible to be more productive with fewer hours?

The truth is, we don’t know how to work remotely. Remote work has become the new norm but how we work has stayed the same. Over the last century, more and more of the workforce has shifted to knowledge work. And recently, where work is done has also changed. It’s time how you work changes too.