[#attention-matters-more-than-time]
== Attention Matters More than Time

Tethered. A single word that describes my relationship with technology. It means to connect. But it also means to tie with a rope or chain to restrict movement. And that’s what technology does to my mind. It connects and restricts me.

Restrict, what an odd choice of words, don’t you think? Technology is often thought of as freeing us from the limitations of the physical world. But what I’ve come to discover is that there is a cost associated with this connectedness. Tethering your phone to your laptop puts more demand on your phone. And so does keeping your mind connected to the digital world. 

It has a cost. Your payments are your productivity and happiness.

Knowledge work has no doors. Never before has this been more true or obvious. That final safeguard has disappeared. There is no longer a factory to shut down. No exit sign to pass under. And no parking lot to escape to. Your work is always there, running in your mind as a background task. Your cell phone has no regard for your time. And your laptop is no more than 20 feet away. You feel like you’re living at work. Because you are.

Why? It doesn’t seem like something anyone would choose. The answer is simple. Responsiveness. When you reward responsiveness above performance it forces you to pull for information. Technology has no shortage of ways to get information. What once kept you connected now keeps you always on. You have apps for email, instant messaging, and push notifications for everything. Maintaining that level of availability is at the core of why you’re unproductive. You've not taken the time to identify what's most important. So, everything is. And when everything is important, nothing is. With so many demands on your attention, your capacity to perform depletes. And it’s depleting faster than you can recharge it.

Caffeine nor a day's rest will restore you. You feel guilty for the day off that you deserve. Being unable to disconnect from the tether has higher costs than you realize. Some costs are obvious and others are hidden.

=== More Time with Less Control

Time was once scarce. But now it isn't. Technology has been giving you back your time. With each decade innovation brings with it more ways to communicate without connecting. Letters no longer require a person to deliver them. Conversations no longer need to be face-to-face. And conferences no longer require a ballroom. Hell, even groceries no longer require a trip to the store. Each of these puts time back in your hourglass. It doesn't feel like you have more time though does it? Instead, the opposite is true, you feel you have less time. You miss those excuses to escape. That commute to work, that drive to the grocery store, and that long lunch with rich conversations. Each gave you something you're now missing, a chance to disconnect.

Life has become a video game you can't put down. Anything without an escape is a trap. But why does it feel this way? Why do you feel less happy with more time? As Morgan Housel points out in his book "The Psychology of Money", the number one predictor of happiness isn't money, fame, or power. It's control over your time. The freedom to do what you want when you want with the time you've been given. Technology has given you more time but has taken with it, control. Control of what? That's a very good question. 

Your attention.

Humor me for a moment. Pull out your phone, and add up all the ways you could be interrupted right now. Count anything that pushes notifications to your screen. Even if you don't have a smartphone you have at least two means of interruption. I started with push notifications because these are the most obvious. You can't argue a flashing light, loud noise, and vibration simultaneously going off in your pocket isn't distracting. Each push is a debit against your attention. It goes beyond that, though. Even with your phone off, it pulls the puppet strings of your attention. 

Roughly 25% of my phone unlocks are prompted by notifications. The remaining 75% are feed driven. I either unlock my phone and immediately start scrolling social media feeds or I open apps that have push notifications and pull for notifications. It is in these two percentiles that I've lost control over my time. It's in my idleness that technology has inflicted the most damage. It has stolen my leisure. Yes, I have more time. But the quality of that time is destroyed by my inability to put down the screen. I never fully disconnect and therefore I never fully recover.
My cell phone usage is driven by one thing, availability. It's the excuse I use to persuade myself that it's worth the cost. I need to be available for my work, friends, and family. What I've learned is that this desire to be available has taken me from them. In my attempt to be reachable, I've become absent in reality. Deaf to their needs, feelings, and desires.

Conversations with friends have evaporated into likes on posts with occasional comments. And my work has also suffered. I favor shallow work instead of digging deep enough to find it within me to output something of true value. Where your attention goes, time follows. You do have time. You're just wasting it.

=== Your Output isn’t in Hours Anymore

Eight-hour workdays are a relic of the past. Even though the workweek remains to be forty hours it's not a useful frame of reference. Knowledge work is much different from an assembly line. Hours are not an accurate means of output. What someone can get done in a single hour can exceed what a team could do in a day or week, given the right conditions and skills.

More time is a horrible amplifier for productivity. Your ability to pay attention and resist distraction is the true amplifier of productivity in today's world.

Your output can't be constant. Knowledge work has a cycle of progress that resembles an athlete instead of a factory worker. Discovery is the first part of any project, which resembles an athlete's training cycle. After discovery is complete, "real work" begins. Everything isn't known. Challenges emerge and adjustments need to be made. Just as an athlete can't predict the weather of an event or an injury at the starting line. Knowledge work is also more demanding than the mindless operating of a machine and rest is required to return to that high level of performance. Most importantly and most often missed is reassessing. Once work has been completed the product, environment, or context are different. More lines of code were added and features were brought into existence. Before an accurate discovery can begin again, reassessing has to be completed and loose ends tied.

In the industrial age, output was in hours. The reason was maximum efficiency had been achieved. It took me too long to realize I hadn't achieved that level of efficiency. And the cost I paid was in hours. Hours, stolen from my family and myself. Both of which I'll never get back.
More hours isn't how you get ahead. Your ability to focus is.


=== Time Management isn’t Enough

I find the statement "I don't have time" hilarious. I'm not judging. I've said it too. It's funny because sitting in your pocket is at least three hours per day. You and I both have time. In fact, the same amount of time. Our cell phone usage is proof of the abundance of time we have. Taking back this time for myself I quickly realized time is only the first constraint of progress. 

Once you have time, you need the ability to focus. In the time you have, your attention becomes your next constraint. Your ability to control your thoughts and to focus your mind is what will get you ahead. 

Time wasted while distracted is even MORE wasteful than time spent in excess leisure.

Most don't realize how finite attention is and how much you must protect it. It's a level deeper than "Protect your time." Time is the surface. If you reclaim your time you'll discover how easily you are distracted. Once you remove distraction, you'll notice that you don't know what to do. Within that space, holding the line and battling out distractions, you'll breathe. The ability to breathe clears your mental space enough to truly reflect. Through reflection, your direction is discerned. And the next step forward demystifies. This is a nearly constant loop that pushes you forward towards your goals.

When I lose this space it feels like someone has thrown me into the middle of a busy intersection. Thoughts become bullets. Each impact increases my anxiety. Unmitigated, it will eventually paralyze me. My vision is reduced, causing me to lose sight of the future I want and battle only for the day at hand. 
The culprits are my own actions. I do it to myself. But I’ve had help.

You and I share a struggle, the modern struggle. You protect those thirty-minute and one-hour blocks on your calendar. But what about those two, three, five, and ten-minute blocks sprinkled throughout your days? Where have the minutes that accumulate to hours gone?

Stop and think about it. You know exactly where that time has gone. It’s what you feel guilty about. And don’t be a fool. You alone are not responsible. An army of scientists & statisticians is against you. They've found a way around your defenses. You protect your time, but not your attention. It’s their trojan horse.
Time management will keep you on track. But it was developed before much of the struggle you and I now face existed. You must concern yourself with how to resist, mitigate, and remove distractions. 

Attention is the gold you think is worthless.
