[#introduction]
= Introduction: My Story

Labels are powerful. They shape who you are by altering your narrative. It's not the labels themselves that are powerful,  it's the meaning you set upon them. That meaning is what shapes the stories you tell yourself and others. With repetition, each builds into your identity.

Reinforced by repetition, identity becomes difficult to change.

One such label for me was, ADD/ADHD. I don't have many memories without that label in bright bold letters on my back. In my elementary years, I struggled to keep up with my class. Mostly in the literary subjects; reading, writing, and spelling. All of which I’m still not great with to this day.

That event changed my internal dialog. You see, I now had an excuse, a scape-goat, for when I was confronted by difficulty. My trump card became, "I can't, I'm stupid." 

It served me for a while. Work became easier, requiring less of me. But with each repetition, my belief in that narrative strengthened. It strengthened to the point at which it became cemented into my identity. My mindset became fixed. I was either naturally good at something or I wasn’t. And if I wasn’t, there wasn’t any reason to exert myself.

Deaf to the praise of my parents, I kept myself well below my potential. My inability to pay attention was genetically determined and therefore out of my control. Or so I thought.

Many years later, at my second job out of college, I took a Strengthfinders test. Imagine my surprise when I found focus not just among my strengths, but my number one strength! I was pleasantly surprised for sure, but also confused. How could they have been so wrong about my abilities? Or were they not wrong? If so, what changed?

In the argument of nature vs. nurture, I found my answer somewhere in between. I don’t believe I was misdiagnosed. It turned out it was a problem to be solved not by pills but by self-education. 

With a stroke of luck, I had found myself in a job that interested me. After spending two years in a community college operating under a “C’s get degrees” mentality, I found myself working in technology. Where, quite ironically, you are forced to be an avid learner. It’s a field where rapid change is the only constant.

At my first job out of college, I took off. For the first time, my performance was tied to more than a grade. I was working at the help desk for a small engineering firm. Perhaps it was partially my small-town charm, but I was rewarded with praise, kindness, and raises for my performance. 

That switched something in me.

Looking around, everyone had an education far beyond a community college degree. So I decided I’d go back to school and aim for my bachelor’s, but aspire to get a master’s. I ended up not achieving either. But I got something even more valuable than a degree. I had learned to apply myself. I completed one full year and walked away with a GPA of 3.8. I leveraged my interests to hone my ability to focus. And then learned to apply that focus to other areas of my life. I taught myself how to focus.

I remember studying the brochure from the University of Nebraska with the same intensity as I had when reading video game manuals in high school.

At my second job, the one where I took the strengthfinders test, I became obsessed with productivity. I embraced my ambitions and let them become my identity. Hoping they’d eclipse what remained of the slacker within. I spent my twenties chasing my ideals in spite of my labels. 

I was simultaneously running from them and proving them wrong.

Fueled by blind ambition I achieved all the goals I set for myself in my early twenties. In my mind, I was at the top. Little did I know life had a surprise for me.

What goes unnoticed is the year that I went dark. I stopped blogging, speaking, reading, and learning. I stopped everything. The reason was I couldn't.

Starting in 2018 I began having health issues. And towards the middle of that year, I entered the darkest moment of my life. Unable to do anything but the absolute minimum, I descended into a world of distractions desperately attempting to escape my existence. I fought hard, but it broke me. First physically, then the chronic pain broke me mentally. I became the worst version of myself. A hollow shell.

I hardly recognized myself. I was 140lbs instead of 175lbs, I became an absent father and husband, and half-assly pulled myself through each workday with my required dose of painkillers to numb myself just enough to skate by. Surprisingly I didn’t get fired, but I would have understood if I did.

After months of increasing levels of pain and doctor visits, I was finally diagnosed. I started treatment and after a short time, the physical pain subsided. Once the veil of suffering lifted I attempted to return to who I was prior. Only to then realize my mind just didn't work as it did before. I had trouble concentrating. My mind wandered within seconds of attempting to focus.

I didn't know if I could return to who I once was. Part of me didn't want to. I had been reduced to an existence. Everything I had worked so hard to improve about myself seemed like a hack. I had spent so much time distracted that it was now all I could do. My ability to focus was completely gone. Perhaps they were right all along. Maybe I was faking it through sheer willpower, willpower I no longer had.

Unaccepting of this reality, I sought answers. 

Fortunately for me, I had started down the path I needed shortly before I got sick. I had actually written about it on my blog. Reading it reminded me of who I once was. I had to get back there. I had grown complacent out of necessity. And the silent suffering of knowing I wasn’t achieving my own potential became unbearable.

As one does when searching for something, I began to read. For the longest time, it was horribly painful to stare into those pages. Inspiration even hurt as it drew a cavern of comparison between who I was and whom I wanted to become. Progress was slow. I kept getting drawn back to be fed. Fed by Facebook, Twitter, YouTube, and even Instagram.

All lasting change requires an overreaction. 

I decided I would take thirty days off all optional technology. My cell phone usage plummeted to ten minutes per day. My computer usage was limited to my working hours. And I'd only watch TV if someone watched it with me. That experience changed me. I found a better version of myself. A version I've been trying to hold on to ever since.

Hitting reset on my digital life made me aware of what Naval Ravikant calls the modern struggle. 

“Lone individuals summoning inhuman willpower,

fasting, meditating, and exercising,

up against armies of scientists & statisticians weaponizing abundant food, screens, & medicine into junk food, clickbait news, infinite porn, endless games & addictive drugs.”

By joining the digital world, you’re also opting into a game. One where companies compete against each other for your attention. It is in that competition that you become their product. And controlling your attention is their aim.

I understand the struggle to hold one’s attention. Perhaps because I’ve struggled with it all my life. I now see that struggle in nearly everyone. Eyes can’t be pulled from screens at restaurants, family events, or even the dinner table. Anxiety is rampant. And people are overwhelmed and frustrated that they cannot seem to make progress on what matters most to them.

In these pages, you will find the lessons I’ve learned, systems, protocols, and methods I’ve created to protect and preserve my attention.

You were meant for more. Life has work you must do. But it also has moments to enjoy for no other reason than the fact you’re alive. Take back your attention, reclaim those moments.