[#introduction]
= Introduction: My Story

Labels are powerful.

They shape who you are by altering the narrative in your head. It's not the labels themselves that are powerful,  it's the meaning you assign them. Meaning is what shapes the stories you tell yourself and others. With repetition, it builds your identity.

Reinforced by repetition, identity becomes difficult to change.

One such label for me was, ADD / ADHD. I don't have many memories without that label in bright bold letters on my back. In my elementary years, I struggled to keep up with my class. Mostly in the literary subjects; reading, writing, and spelling. Eventually the gap was to wide and I was put into a special class for those subjects.

That event changed my internal dialog. You see, I now had an excuse, a scape-goat, for when I was confronted by difficulty. My trump card became, "I can't, I'm stupid."

Work became easier and less was required of me. But with each utterance of the phrase "I'm stupid", my belief in that narrative strengthened. It strengthened to the point at which it became cemented into my identity. My mindset became fixed. I believed I was either naturally good at something or I wasn’t. And if I wasn’t, there wasn’t any reason to exert myself.

Deaf to the praise of my parents, I kept myself well below my potential. My inability to pay attention was genetically determined and therefore out of my control. Or so I thought.

Many years later, at my second job out of college, I took a Strengthfinders test. Imagine my surprise when I found **focus not just among my strengths, but my number one strength**! I was pleasantly surprised, but also confused.

How could they have been so wrong about me? Or were they not wrong? If so, what changed?

In the argument of nature vs. nurture, I found my answer somewhere in between. I don’t believe I was misdiagnosed. It turned out it was a problem to be solved not by pills but by self-education.

With a stroke of luck, I had found myself in a job that interested me. After spending two years in a community college operating under a “C’s get degrees” mentality, I landed a job in technology. Where, quite ironically, you are forced to be an avid learner. It’s a field where rapid change is the only constant. It was this job that changed everything. For the first time my performance was tied to more than a grade. Perhaps it was partially my small-town charm, but I was rewarded ith praise, kindness, and raises for my hard work. And that switched something in me.

I remember studying the brochure from the University of Nebraska with the same intensity as I had when reading video game manuals in high school.

As I Looked around at my peers, everyone had an education far beyond a community college degree. So I decided I’d go back to school and aim for my bachelor’s, but aspire to get a master’s. I ended up not achieving either. But that experience left me with something even more valuable than a degree. I had learned to apply myself. I completed one full year and walked away with a GPA of 3.8. The highest GPA average I had ever achieved in my life!

I leveraged my interests to hone my ability to focus. Then used that focus on other areas of my life. In essence, I taught myself how to focus.

At my second job, the one where I took the StrengthFinders test, I became obsessed with productivity. I embraced my ambitions and let them become my identity. Hoping they’d eclipse what remained of the slacker within. I spent my twenties chasing my ideals in spite of my labels.

I was simultaneously running from them and proving them wrong.

Fueled by blind ambition I achieved everything I set out to my early twenties. It was through self-education that I broke free of my fixed mindset and transformed it into a growth mindset.

Productivity ruled my life. I began to squeeze every ounce of progress out of my days. Idleness and boredom became my enemies, and the rapid innovation of smart phones were my secret weapon. Each year that device in my pocket empowered me to do more. Through it I was always learning, growing, and doing. My justification was a better future, for me and my family. I had valid reasons to always be connected. Email was going to get me that next promotion. Twitter was going to unsure I was in the know. LinkedIn ensured recruiters saw my resume. And YouTube kept my knowledge sharp while entertaining me enough that tears of boredom never left my eyes.

My life became a series of sprints run within a hamster wheel. Each race started out in a dead sprint. I'd do and consume as much as possible, pushing myself to my limits. Without the concept of rest or recovery I became reliant on willpower. Eventually my willpower would deplete and I'd collapse. Exhaustion lead to burnout and burnout brought on a wave of self-loating. Tiring of self-loating I'd pick myself back up and the cycle would begin again. I kept this pace throughout most of my twenties.

// Insert graphic here with a circle depicting the cycle.

It wasn't until the demands of life increased that I realized the dangers of productivity. Fatherhood put a time constraint on me that I wasn't prepared for. Time had always been in abundance and now it was scarce. My fragile hamster wheel started to break much more frequently forcing me into a cycle of burnout every few weeks or months. __I felt like I was running on empty all the time__. Relying solely on willpower wasn’t working. I knew I needed to find ways to protect, preserve, and restore my mental energy.

Answers started to come from unexpected places.

//The Shallows

// Started to have an impact on my family life, unwilling to sacrifice.

// productivity hamster wheel (sprint, burn-out, slight depression, self lothing, get back up) unsustainable

// A new problem arose productivity.

\\ --> Missing time period leading up to detaching from distraction
\\ --> Tie increasing technology usage to running on empty all the time.

I had built a house of cards and it came crashing down.

In my mind, I was at the top. But little did I know, life had a surprise waiting for me.

What goes unnoticed is the year that I went dark. I stopped blogging, speaking, reading, and learning. I stopped everything. The reason was I couldn't.

Starting in 2018 I began having health issues. And towards the middle of that year, I entered the darkest moment of my life. Unable to do anything but the absolute minimum, I descended into a world of distractions desperately attempting to escape my existence. I fought hard, but it broke me. First physically, then the chronic pain broke me mentally. I became the worst version of myself. A hollow shell.

I hardly recognized myself. I was 140lbs instead of 175lbs, I became an absent father and husband, and half-assly pulled myself through each workday with my required dose of painkillers to numb myself just enough to skate by. Surprisingly I didn’t get fired, but I would have understood if I did.

After months of increasing levels of pain and doctor visits, I was finally diagnosed. I started treatment and after a short time, the physical pain subsided. Once the veil of suffering lifted I attempted to return to who I was prior. Only to then realize my mind just didn't work as it did before. I had trouble concentrating. My mind wandered within seconds of attempting to focus.

I didn't know if I could return to who I once was. Part of me didn't want to. I had been reduced to an existence. Everything I had worked so hard to improve about myself seemed like a hack. I had spent so much time distracted that it was now all I could do. My ability to focus was completely gone. Perhaps they were right all along. Maybe I was faking it through sheer willpower, willpower I no longer had.

Unaccepting of this reality, I sought answers.

Fortunately for me, I had started down the path I needed shortly before I got sick. I had actually written about it on my blog. Reading it reminded me of who I once was. I had to get back there. I had grown complacent out of necessity. And the silent suffering of knowing I wasn’t achieving my own potential became unbearable.

As one does when searching for something, I began to read. For the longest time, it was horribly painful to stare into those pages. Inspiration even hurt as it drew a cavern of comparison between who I was and whom I wanted to become. Progress was slow. I kept getting drawn back to be fed. Fed by Facebook, Twitter, YouTube, and even Instagram.

All lasting change requires an overreaction.

I decided I would take thirty days off all optional technology. My cell phone usage plummeted to ten minutes per day. My computer usage was limited to my working hours. And I'd only watch TV if someone watched it with me. That experience changed me. I found a better version of myself. A version I've been trying to hold on to ever since.

Hitting reset on my digital life made me aware of what Naval Ravikant calls the modern struggle.

“Lone individuals summoning inhuman willpower,

fasting, meditating, and exercising,

up against armies of scientists & statisticians weaponizing abundant food, screens, & medicine into junk food, clickbait news, infinite porn, endless games & addictive drugs.”

By joining the digital world, you’re also opting into a game. One where companies compete against each other for your attention. It is in that competition that you become their product. And controlling your attention is their aim.

I understand the struggle to hold one’s attention. Perhaps because I’ve struggled with it all my life. I now see that struggle in nearly everyone. Eyes can’t be pulled from screens at restaurants, family events, or even the dinner table. Anxiety is rampant. And people are overwhelmed and frustrated that they cannot seem to make progress on what matters most to them.

In these pages, you will find the lessons I’ve learned, systems, protocols, and methods I’ve created to protect and preserve my attention.

You were meant for more. Life has work you must do. But it also has moments to enjoy for no other reason than the fact you’re alive. Take back your attention, reclaim those moments.