[#introduction]
= Introduction: My Story

I went dark. I stopped blogging, speaking, and learning. The reason was I couldn't. Starting in 2018 I began having health issues. And towards the middle of that year, I entered the darkest moment of my life. After six months of increasing levels of pain and doctor visits, I was finally diagnosed.

I fought hard, but it broke me. First I broke physically. Then dealing with chronic pain I eventually broke mentally. I became the worst version of myself. A hollow shell. Unable to do nothing but the absolute minimum. I descended into a world of distractions desperately attempting to escape my existence. 

I started treatment. And after a short time, the physical pain subsided. Once the veil of suffering lifted I attempted to return to who I was prior. Only to then realize what once had given my life meaning and joy left me numb. I didn't know if I could return to who I once was. Part of me didn't want to. 

My mind just didn't work as it did before. I had trouble concentrating. My mind wandered within seconds of attempting to focus. Throughout my life, I've not been known for my ability to focus. I was labeled with ADD as a child and now it felt they were right. Unaccepting of this reality, I sought answers. As one does when searching for something, I began to read. 

The decision to pick up the mantel of self-improvement was the key moment and catalyst for where I am today. I've been on this part of my journey for a little over two years now. Looking back I wouldn't change what I went through. Having fortified myself in many ways I'm a better version of myself than I ever was.

As I rebuild who I was brick by painstaking brick, I discovered something. 

Time isn’t your most valuable resource. **Your attention is**.