[#side-effects-of-usage]
== Side-effects of Usage

Life without is blissful. Life with is abundant.

I can feel it, the low-level anxiety has returned. Unable to stand still I mindlessly rush through my days. Compelled by impulse, I pick up my phone. 

Are there any calls, texts, messages, likes? What about my bank account? Is that okay? 

Each pickup is a cycle of fear, driven by the hope of dopamine.

It's happened again. I'm **oversubscribed**.

Several years ago I took thirty days off all optional technology. My cell phone usage dropped to then minutes per day. My computer usage was limited to my working hours. And I'd only watch TV if someone watched it with me. That experience changed me. You don't know me, but if you did and someone said I was calm you'd laugh. But that's what happened. I became calm. Not only that I became focused.

Within those thirty days, I found a better version of myself. A version I've been trying to hold on to ever since.

My fondest memory of those blissful thirty days was a habit I wish had stuck. Each morning before my family was awake I'd make some coffee, grab a book, and walk outside.

There, on my front porch, I'd sit. Reading and enjoying a cup of coffee as the sun came up. It's hard to start a bad day off like that.

Each of those mornings had a cost. Disconnected, I missed out. I could have been using that time to be "productive". It is time I could have been spent writing, recording, building, or learning new skills to further my career. 

The internet provides an abundance of opportunities.

Fearing I had missed out on too much, I returned. Twitter and YouTube found their way back on my phone. Using my phone at the dinner table also became an issue again. My daily cell phone usage climbed to an hour then two. Not quite reaching my previous benchmark of three hours per day, but enough that my calmness begain to fade.

As I connect to more and more things I feel more productive. But when I objectively look at my output I realize I was lying to myself. The productivity I felt was an illusion. I was doing a lot of what didn't matter and trying to convince myself it did. 

That connectedness had hidden costs.

// __The Shallows: The Juggler's Brain__ what returning to abundance does.

When I have veered too far from blissful, I hit **reset**.

I've spent the last several years exploring the line between these two worlds. What I'm attempting to learn is to __live in blissful abundance__.  Mindfulness and productivity are not opposites, they are dependencies.

To help me find my way back, I've drawn a map. This book is that map.

