name: "publish"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  publish-to-gumroad:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.4

    - name: Create PDF with asciidoctor-pdf
      uses: ./.github/actions/asciidoctor
      with:
        file: reclaim.adoc

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Copy Book to AWS S3
      run: |
        aws s3 cp reclaim.pdf s3://duffneyio/books/ --acl public-read