name: "publish"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  publish-to-gumroad:
    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v2.3.4

    - name: asciidoctor-pdf
      uses: ./.github/actions/asciidoctor
      with:
        file: reclaim.adoc
    
    - name: test
      run: "[ -f reclaim.pdf ] && echo 'File exist' || echo 'File does not exist'"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: copy book to s3
      run: |
        aws s3 cp reclaim.pdf s3://duffneyio/books/ --acl public-read